logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p [%thread] %logger{36} : %msg %kvp%n"

management:
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: eshop-api
    distribution:
      percentiles-histogram:
        http.server.requests: true
        cms.directus.request: true

app:
  security:
    directus-bridge-token: ${DIRECTUS_BRIDGE_TOKEN:}
  observability:
    prometheus-token: ${APP_OBSERVABILITY_PROMETHEUS_TOKEN:}
